/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Interfaz_gráfica;

import GestionBBDD.Gestion_BBDD;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author eduardolucasmunozdelucas
 */
public class IngresarEmpleados extends javax.swing.JDialog {

    Gestion_BBDD gesBBDD = new Gestion_BBDD();
    ArrayList<Empleado> lista_empleados = new ArrayList<>();
    Connection con = gesBBDD.Conectarse();
    private Empleado empleado;

    /**
     * Creates new form IngresarEmpleados
     */
    public IngresarEmpleados(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        lista_empleados = gesBBDD.cargar_listado_empleados(con);
        if (lista_empleados.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No existe ningún empleado en la BBDD", "Error", JOptionPane.WARNING_MESSAGE);
            gesBBDD.desconectarse(con);
            dispose();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_surname = new javax.swing.JTextField();
        tf_tlf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tf_email = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        bt_aceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_user = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bt_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel5.setText("Teléfono:");

        jLabel6.setText("email:");

        tf_surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_surnameActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        bt_aceptar.setText("Ingresar");
        bt_aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_aceptarActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario:");

        jLabel7.setText("Ingresa los datos del nuevo empleado");

        jLabel3.setText("Password:");

        jLabel4.setText("Apellido:");

        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(bt_aceptar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(tf_nombre)
                                .addComponent(tf_user)
                                .addComponent(tf_pass)
                                .addComponent(tf_surname)
                                .addComponent(tf_tlf)
                                .addComponent(tf_email, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt_salir)
                                .addGap(88, 88, 88))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel7)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tf_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_tlf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tf_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bt_aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(bt_salir)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_surnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_surnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_surnameActionPerformed

    private void bt_aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_aceptarActionPerformed

        if (tf_user.getText().trim().isEmpty()
                || tf_pass.getText().trim().isEmpty()
                || tf_nombre.getText().trim().isEmpty()
                || tf_surname.getText().trim().isEmpty()
                || tf_email.getText().trim().isEmpty()
                || tf_tlf.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debes rellenar todos los campos", "Faltan campos por rellenar", JOptionPane.WARNING_MESSAGE);
            return;
        }

        for (Empleado em : lista_empleados) {
            if (tf_user.getText().equalsIgnoreCase(em.getUser())) {
                JOptionPane.showMessageDialog(this, "El usuario " + tf_user.getText() + " ya existe debes elegir otro", "Error en el campo usuario", JOptionPane.WARNING_MESSAGE);
                return;
            }

        }

        for (Empleado em : lista_empleados) {
            if (tf_nombre.getText().equalsIgnoreCase(em.getName()) && tf_surname.getText().equalsIgnoreCase(em.getSurname())) {
                JOptionPane.showMessageDialog(this, "El usuario " + tf_nombre.getText() + " " + tf_surname.getText() + " ya existe debes elegir otro nombre o apellido", "Error con el nombre y apellido", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }

        String user = tf_user.getText().trim();
        String pass = tf_pass.getText().trim();
        String name = tf_nombre.getText().trim();
        String surname = tf_surname.getText().trim();
        String email = tf_email.getText().trim();
        String tlfTexto = tf_tlf.getText().trim();

        // Verifica que el campo no esté vacío y solo contenga números
        if (tlfTexto.isEmpty() || !tlfTexto.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "El nº de teléfono debe contener solo números y no estar vacío", "Error en el nº de teléfono", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int tlf = Integer.parseInt(tlfTexto); // Ahora es seguro convertirlo

        // Verifica que tenga exactamente 9 dígitos
        if (tlfTexto.length() != 9) {
            JOptionPane.showMessageDialog(this, "El nº de teléfono debe tener exactamente 9 dígitos", "Error en el nº de teléfono", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //System.out.println("--> " + user + pass + name + surname + tlf + email);
        empleado = new Empleado(user, pass, name, surname, tlf, email);
        Connection con = gesBBDD.Conectarse();
        if (gesBBDD.Insertar_empleado(con, empleado)) {
            JOptionPane.showMessageDialog(this, "EMpleado insertado con éxito", "Empleado insertado", JOptionPane.INFORMATION_MESSAGE);
            gesBBDD.desconectarse(con);

            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Error en la conexión con la BBDD", "Error", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_bt_aceptarActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        gesBBDD.desconectarse(con);
        dispose();
    }//GEN-LAST:event_bt_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresarEmpleados dialog = new IngresarEmpleados(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_aceptar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf_email;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_pass;
    private javax.swing.JTextField tf_surname;
    private javax.swing.JTextField tf_tlf;
    private javax.swing.JTextField tf_user;
    // End of variables declaration//GEN-END:variables
}
